### ISSUE TITLE
Combat fixes tracking 

### ISSUE THREAD

**Issue by Woynert** [PedroChaparro/loomies-backend#108]
I've create this issue in order to track the different fixes / improvements required for the combat system.

- [ ] Token can be obtained from far gyms: When fetching */combat/register* you can specify any gym even if it is out of reach; a token will be received and this token will fail when trying to enter the actual combat.
- [ ] There is no dedicated *Message type* when the combat ends, timeout.
- [ ] There timeout is too short. Maybe increase it somewhere around 30 minutes.
